default_language_version:
  python: python3

repos:
  # Should be enabled either yapf or black once this branch is merged
  # - repo: https://github.com/google/yapf.git
  #   rev: v0.40.1
  #   hooks:
  #     - id: yapf

  - repo: https://github.com/psf/black.git
    rev: 23.11.0
    hooks:
      - id: black
        args:
          - --config=pyproject.toml

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.1.5
    hooks:
      - id: ruff
        args:
          - --config=pyproject.toml

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      # list of supported hooks: https://pre-commit.com/hooks.html
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: debug-statements
      - id: detect-private-key
      - id: check-executables-have-shebangs
      - id: check-toml
      - id: check-case-conflict
      - id: check-added-large-files

  # md formatting
  - repo: https://github.com/executablebooks/mdformat.git
    rev: 0.7.17
    hooks:
      - id: mdformat
        args: ["--number"]
        additional_dependencies:
          - mdformat-gfm
          - mdformat-tables
          - mdformat_frontmatter

  # jupyter notebook cell output clearing
  - repo: https://github.com/kynan/nbstripout
    rev: 0.6.1
    hooks:
      - id: nbstripout

  # jupyter notebook linting
  - repo: https://github.com/nbQA-dev/nbQA.git
    rev: 1.7.0
    hooks:
      - id: nbqa-ruff
        args:
          - --config=pyproject.toml
          - --ignore=F811,F821,D417

  # # add pytest
  # - repo: local
  #   hooks:
  #   - id: run_pytest
  #     language: script
  #     name: Run tests
  #     entry: ./run_test.bat
  #     stages: [commit]

  # - repo: https://github.com/google/pytype
  #   # Ruff version.
  #   rev: 2023.09.11
  #   hooks:
  #     - id: pytype
  #       # args:
  #       #   - --config=pyproject.toml
