# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Publish Docker image

on:
  push:
    branches:
      - master
    tags:
      - v*

permissions: write-all

jobs:
  build_base_images:
    name: Build and Push Base Images
    runs-on: ubuntu-latest
    # container: catthehacker/ubuntu:act-20.04  # Uncomment it if you use it on Gitea

    strategy:
      fail-fast: true
      max-parallel: 3
      matrix:
        target:
          - name: Build and Push Image (Base)
            target_step: repo_base
            tag: ${{ vars.IMAGE }}-base
            build_args: --build-arg PYTHON_VERSION=3.10.14

          - name: Build and Push Image (Develop Base)
            target_step: repo_dev_base
            tag: ${{ vars.IMAGE }}-dev-base
            build_args: --build-arg PYTHON_VERSION=3.10.14

          - name: Build and Push Images (Latest / Release)
            target_step: repo
            tag: ${{ vars.IMAGE }}
            build_args: --build-arg PYTHON_VERSION=3.10.14

    steps:
      - name: Disable SSL Verify
        run: git config --global http.sslVerify false

      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 1
          submodules: 'recursive'

      - name: Login to the Container registry
        uses: docker/login-action@v3.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Latest Image
        uses: docker/build-push-action@v5.1.0
        with:
          push: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          file: ./docker/Dockerfile
          build-args: ${{ matrix.target.build_args }}
          target: ${{ matrix.target.target_step }}
          tags: ${{ matrix.target.tag }}:latest
          sbom: false
          provenance: false

      - name: Get the version
        if: startsWith(github.ref, 'refs/tags/v')
        id: metadata
        uses: battila7/get-version-action@v2

      - name: Build and Push Base Image
        if: startsWith(github.ref, 'refs/tags/v')
        uses: docker/build-push-action@v5.1.0
        with:
          push: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          file: ./docker/Dockerfile
          build-args: ${{ matrix.target.build_args }}
          target: ${{ matrix.target.target_step }}
          tags: ${{ matrix.target.tag }}:${{ steps.metadata.outputs.version }}
          sbom: false
          provenance: false
